#!/bin/sh
### BEGIN INIT INFO
# Provides:          pulsedb
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop pulsedb server
### END INIT INFO

if [ -d /opt/pulsedb -a ! -f ebin/pulsedb.beam ] ; then
  # Launching in linux

  export LOGDIR=/var/log/pulsedb
  export HOME=/var/lib/pulsedb

  if [ `whoami` != 'pulsedb' ] ; then
    exec su -m pulsedb $0 $*
  fi

  cd /opt/pulsedb
fi


case $1 in
"start")
  erl -env ERL_LIBS deps:.. -pa ebin -detached -name pulsedb@127.0.0.1 -s pulsedb_launcher
  ;;
"stop")
  erl -name debug@127.0.0.1 -eval "rpc:call('pulsedb@127.0.0.1', erlang, halt, [0]), erlang:halt(0)" -detached
  ;;
"run")
  erl -env ERL_LIBS deps:.. -pa ebin -name pulsedb@127.0.0.1 -s pulsedb_launcher
  ;;
"shell")
  erl -name debug@127.0.0.1 -remsh pulsedb@127.0.0.1
  ;;
*)
  echo "$0 start|stop|run|shell"
esac

