#!/bin/sh

# if [ ! -d /etc/init ] ; then
update-rc.d pulsedb defaults 80 80
# fi

adduser --system --home /var/lib/pulsedb --disabled-password --gecos "" pulsedb 

mkdir /var/log/pulsedb
chown pulsedb /var/log/pulsedb

invoke-rc.d pulsedb start

